### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by somedevreally** [Inlustra/auto-docker-dash#5]
am getting this error, latest docker version

```
today at 12:57:59 info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
today at 12:58:00 > Server listening at http://localhost:3000 as production
today at 12:58:00 undefined
today at 12:59:17 undefined
today at 12:59:17 Docker Setup
today at 12:59:17 Docker Pinged
today at 12:59:17 Docker Setup
today at 12:59:17 Docker Pinged
today at 12:59:17 undefined
today at 12:59:17 undefined
today at 12:59:17 undefined
today at 12:59:17 undefined
today at 12:59:18 undefined
today at 12:59:19 undefined
today at 12:59:20 undefined
today at 12:59:21 undefined
today at 12:59:22 undefined
today at 12:59:24 undefined
today at 12:59:28 undefined
today at 12:59:35 undefined
today at 12:59:35 undefined
today at 12:59:35 undefined
today at 12:59:35 undefined
today at 12:59:36 undefined
today at 12:59:37 undefined
today at 12:59:37 undefined
today at 12:59:37 undefined
today at 12:59:41 undefined
today at 12:59:41 undefined
today at 12:59:41 undefined
today at 12:59:41 undefined
today at 12:59:42 undefined
today at 12:59:43 undefined
today at 12:59:43 undefined
today at 12:59:43 undefined
today at 12:59:44 undefined
today at 12:59:46 undefined
today at 12:59:50 undefined
today at 12:59:59 undefined
today at 13:00:07 undefined
today at 13:00:10 undefined
today at 13:00:10 undefined
today at 13:00:10 undefined
today at 13:00:10 undefined
today at 13:00:11 undefined
today at 13:00:12 undefined
```

**Comment by Inlustra** [comment]
Is the server not running at all? (That looks suspiciously like me having left a console log in somewhere if not)

**Comment by somedevreally** [comment]
server is running, docker says OK with green line, uptime is in yellow

**Comment by Inlustra** [comment]
If uptime is yellow, but it looks like it's updating fine. That usually just means that your server and local clock are out of sync ever so slighty - I'll be fixing that soon enough! 

As for the logging, I'm going to publish some changes to remove all console logs for production, they'll be filling up your logs for no reason! 

Thanks for update :)

**Comment by somedevreally** [comment]
ok cool. will wait for update.
another quick question, when the container is down, should it show as red? and what is the scan interval?
i removed the container and i still shows it as green.

**Comment by Inlustra** [comment]
That does suggest that something is awry! Scan interval is currently set to 5 seconds.
Currently the `exited` docker status is grey, `dead` is red.
Can you check your console? Do you see anything about websockets by any chance?

**Comment by somedevreally** [comment]
nothing on console, just flooded with undefined

**Comment by Inlustra** [comment]
Including console on the web?

**Comment by somedevreally** [comment]
on web console: 
` WebSocket connection to 'ws://my.tld/graphql' failed: `

**Comment by somedevreally** [comment]
oh that error was on my side, i enabled websocket support with npm, but that container disappeared from daashboard

**Comment by Inlustra** [comment]
If the container doesn't even appear in the container list within docker, it's unfortunately not going to appear in the dashboard as there's no way of knowing about it. 
Does your container appear in `docker container ls -a`?

**Comment by somedevreally** [comment]
ok 
running = green
stopped = grey
removed = do not exit

**Comment by Inlustra** [comment]
I'll add some info about it to the README :) 

dead = red
yellow = restarting/starting

**Comment by somedevreally** [comment]
in nginx proxy, when mapping the proxy host, there is option to enable websockets, which was disabled by default, after enabling everything works as expected. even the undefined log is gone ;)
```
today at 13:47:43 Docker Setup
today at 13:47:43 Docker Pinged
today at 13:47:48 Docker Setup
today at 13:47:48 Docker Pinged
today at 13:47:53 Docker Setup
today at 13:47:53 Docker Pinged

```

**Comment by somedevreally** [comment]
awesome project, thank you.
only thing now needed is alert when contains are down?

**Comment by Inlustra** [comment]
Yep, there's next to no error handling within the app or alerts when things actually go down - I currently have it only refreshing when someone is looking at the page (By design) It would be easy to change that. 

Although I do feel like there might be better alerting solutions and that's not really the aim of this project!
